/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agentapp;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Nilesh
 */
public class oppenaccount extends javax.swing.JFrame {

    /**
     * Creates new form oppenaccount
     */
      String s;
       Connection conn = null;
      ResultSet r;
    Statement st;
     PreparedStatement ps;
     int risultato;
      int n;
         int bal1;
         String accno1;
         String agentno;
    public oppenaccount() {
        initComponents();
         
        
    }
    
    
    
    //resize the original photo
     public ImageIcon ResizeImage(String imgPath){
        ImageIcon MyImage = new ImageIcon(imgPath);
        Image img = MyImage.getImage();
        Image newImage = img.getScaledInstance(cphoto.getWidth(), cphoto.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImage);
        return image;
    }

     //connect to database
     public void connectiondb()
            {
               String databaseURL = "jdbc:mysql://localhost:3306/db_hlbank";
        String user = "root";
        String password = "";
       
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(databaseURL,user,password);
            if (conn != null) {
                System.out.println("Connected to the database");
            }
            else
            {
                System.out.println("Connection error");
            }
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(oppenaccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(oppenaccount.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog3 = new datechooser.beans.DateChooserDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uid1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cfname = new javax.swing.JTextField();
        clname = new javax.swing.JTextField();
        cphoto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cpass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ccpass = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cemail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cphone = new javax.swing.JTextField();
        cdob = new datechooser.beans.DateChooserCombo();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cgender = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        caopendate = new datechooser.beans.DateChooserCombo();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cadd = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        ccity = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cstate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        ccountry = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        czip = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        nominal = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        camount = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        cnominal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create New Account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(uid1)
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uid1)
                    .addComponent(jLabel1)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personal Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("First Name :");

        jLabel4.setText("Last Name :");

        cphoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel6.setText("Photo");

        jLabel7.setText("Password :");

        jLabel8.setText("Confirm Password :");

        jLabel9.setText("Email Address :");

        jLabel10.setText("Contact number :");

        jLabel11.setText("Date of Birth :");

        jLabel12.setText("Gender  :");

        cgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "male", "female" }));

        jLabel13.setText("Photo :");

        jButton1.setText("Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Open Date :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(24, 24, 24)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(57, 57, 57)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cemail, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(cfname)
                                .addComponent(cpass)))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(54, 54, 54)
                                        .addComponent(clname))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cphone)
                                            .addComponent(ccpass)
                                            .addComponent(cgender, 0, 143, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(caopendate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(cfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(ccpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(cdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(cgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(cphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(caopendate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address Information :");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setText("Address :");

        cadd.setColumns(20);
        cadd.setRows(5);
        jScrollPane1.setViewportView(cadd);

        jLabel17.setText("City :");

        jLabel18.setText("State :");

        jLabel19.setText("Country :");

        jLabel20.setText("Zip Code :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(czip))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(ccity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cstate)))
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(ccountry, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ccity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ccountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(cstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(czip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Account Information :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel23.setText("Daily Amount :");

        jLabel24.setText("Nominal Name :");

        jButton2.setText("Open Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel25.setText("Pin :");

        javax.swing.GroupLayout nominalLayout = new javax.swing.GroupLayout(nominal);
        nominal.setLayout(nominalLayout);
        nominalLayout.setHorizontalGroup(
            nominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nominalLayout.createSequentialGroup()
                .addGroup(nominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nominalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(camount, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nominalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cnominal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nominalLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nominalLayout.setVerticalGroup(
            nominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nominalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(camount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(cnominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(nominalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nominal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nominal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
         fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg","gif","png");
         fileChooser.addChoosableFileFilter(filter);
         int result = fileChooser.showSaveDialog(null);
         if(result == JFileChooser.APPROVE_OPTION){
             File selectedFile = fileChooser.getSelectedFile();
             String path = selectedFile.getAbsolutePath();
             cphoto.setIcon(ResizeImage(path));
             s = path;
              }
         else if(result == JFileChooser.CANCEL_OPTION){
             System.out.println("No Data");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try {                                         
          String fname=cfname.getText();
          String lname=clname.getText();
          String pass=cpass.getText();
          String cpass=ccpass.getText();
          String email=cemail.getText();
          String phone=cphone.getText();
         String dob= cdob.getText();
          String gender=cgender.getSelectedItem().toString();
          SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy");
          String date = sdf.format(caopendate.getSelectedDate().getTime());
          String add=cadd.getText();
          String city=ccity.getText();
          String country=ccountry.getText();
          String state=cstate.getText();
          String zip=czip.getText();
          
          String am=camount.getText();
          String p=pin.getText();
          String nominal=cnominal.getText();
          
          
          
          
// validation for all controls

int validation=0;

String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
Boolean b = email.matches(EMAIL_REGEX);
System.out.println(b);

Pattern pattern = Pattern.compile("\\d{2}-\\d{10}");
Matcher matcher = pattern.matcher(phone);

Pattern pattern1 = Pattern.compile("\\d{6}");
Matcher matcher1 = pattern1.matcher(zip);

DateFormat df = new SimpleDateFormat("dd/MM/yy");
Date dateobj = new Date();
System.out.println(df.format(dateobj));

SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yy");
String udate = sdf2.format(cdob.getSelectedDate().getTime());

Date date2 = df.parse(udate);



SimpleDateFormat sdf3 = new SimpleDateFormat("dd/MM/yy");
String udate1 = sdf3.format(caopendate.getSelectedDate().getTime());
Date date3 = df.parse(udate1);

if (!matcher1.matches()) {
                JOptionPane.showMessageDialog(null, "zip code enter 6 digit number");
                validation=1;
            }

if(date3.after(dateobj)){
    JOptionPane.showMessageDialog(null, "Please check open Date");
    validation=1;
}
else if(date2.after(dateobj)){
    JOptionPane.showMessageDialog(null, "Check date of birth");
    validation=1;
}
else if (!matcher.matches()) {
    JOptionPane.showMessageDialog(null, "Phone Number must be in the form XX-XXXXXXXXXX");
    validation=1;
}


else if(b==false)
{
    JOptionPane.showMessageDialog(null, "Please enter valid Email id");
    validation=1;
}



else if(fname.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid first name");
    validation=1;
}
else if(lname.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid last name");
    validation=1;
}
else if(cpass.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid password");
    validation=1;
}
else if(pass.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid password");
    validation=1;
}
else if(!pass.equals(cpass))
{
    JOptionPane.showMessageDialog(null, "Password does not match");
    validation=1;
}
else if(email.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid email");
    validation=1;
}
else if(phone.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid contact number");
    validation=1;
}
else if(dob.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid dob");
    validation=1;
}
else if(cgender.getSelectedIndex()==0)
{
    JOptionPane.showMessageDialog(null, "Please enter valid gender");
    validation=1;
}
else if(add.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid address");
    validation=1;
}
else if(city.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid City");
    validation=1;
}
else if(country.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid Country");
    validation=1;
}
else if(state.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid State");
    validation=1;
}

else if(zip.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid zip");
    validation=1;
}

else if(nominal.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid nominal name");
    validation=1;
}
else if(am.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid amount");
    validation=1;
}
else if(p.isEmpty())
{
    JOptionPane.showMessageDialog(null, "Please enter valid pin");
    validation=1;
}


//validation with database
connectiondb();
try {
    ps=conn.prepareStatement("SELECT `email`FROM `tbl_users` WHERE `email`=?");
    ps.setString(1,cemail.getText());
    ResultSet result=ps.executeQuery();
    
    if(result.next())
    {
        JOptionPane.showMessageDialog(null, "Email address is already register");
        validation=1;
        
    }
    
} catch (SQLException ex) {
    Logger.getLogger(oppenaccount.class.getName()).log(Level.SEVERE, null, ex);
}

try {
    ps=conn.prepareStatement("SELECT `phone` FROM `tbl_users` WHERE `phone`=?");
    ps.setString(1,cphone.getText());
    ResultSet result=ps.executeQuery();
    
    if(result.next())
    {
        JOptionPane.showMessageDialog(null, "contact no is already register");
        validation=1;
    }
    
} catch (SQLException ex) {
    Logger.getLogger(oppenaccount.class.getName()).log(Level.SEVERE, null, ex);
}

try {
    ps=conn.prepareStatement("SELECT `pin` FROM `tbl_accounts` WHERE `pin`=?");
    ps.setString(1,pin.getText());
    ResultSet result=ps.executeQuery();
    
    if(result.next())
    {
        JOptionPane.showMessageDialog(null, "pin number is already register");
        validation=1;
    }
    
} catch (SQLException ex) {
    Logger.getLogger(oppenaccount.class.getName()).log(Level.SEVERE, null, ex);
}






if(validation==0)
{
    
    
    
    
    
    
    try{
        
        PreparedStatement ps =conn.prepareStatement("INSERT INTO `tbl_users`(`fname`, `lname`, `pwd`, `email`, `phone`, `gender`, `is_active`, `utype`, `pics`, `bdate`) VALUES(?,?,?,?,?,?,?,?,?,?)",PreparedStatement.RETURN_GENERATED_KEYS);
        InputStream is = new FileInputStream(new File(s));
        ps.setString(1, cfname.getText());
        ps.setString(2,clname.getText());
        ps.setString(3,ccpass.getText());
        ps.setString(4,cemail.getText());
        ps.setString(5,cphone.getText());
        ps.setString(6,cgender.getSelectedItem().toString());
        String active="FALSE";
        ps.setString(7,active);
        String ut="USER";
        ps.setString(8,ut);
        ps.setBlob(9,is);
        
        SimpleDateFormat db = new SimpleDateFormat("dd/MM/yy");
        String dob1 = db.format(cdob.getSelectedDate().getTime());
        ps.setString(10,dob1);
        ps.executeUpdate();
        ResultSet rs = ps.getGeneratedKeys();
        if (rs.next()){
            risultato=rs.getInt(1);
            
            //fill data into address table
            PreparedStatement ps1 =conn.prepareStatement("INSERT INTO `tbl_address`(`user_id`, `address`, `city`, `state`, `zipcode`, `country`) VALUES (?,?,?,?,?,?)");
            ps1.setInt(1,risultato);
            ps1.setString(2,add);
            ps1.setString(3,city);
            ps1.setString(4,state);
            ps1.setString(5,zip);
            ps1.setString(6,country);
            ps1.executeUpdate();
            
            //fill data into agent account table
            //getting current agent account no
            int a1 = Integer.parseInt(uid1.getText());
            System.out.println(a1);
            PreparedStatement ps5=conn.prepareStatement("SELECT `accountno` FROM `tbl_agentaccount` WHERE `agentid`=?");
            ps5.setInt(1,a1);
            ResultSet result9=ps5.executeQuery();
            
            if(result9.next())
            {
                agentno=result9.getString("accountno");
                System.out.println(agentno);
            }
            
            
            
            //random number logic
            Random ran=new Random();
            n=100000+ran.nextInt(900000);
            System.out.println(n);
            
            //expriy date logic
          
             String exp = sdf.format(caopendate.getSelectedDate().getTime());
            
           
       Calendar c = Calendar.getInstance();
        c.setTime(caopendate.getSelectedDate().getTime()); // Now use today date.
        c.add(Calendar.MONTH,6); // Adding 5 days
String output = sdf.format(c.getTime());
            
            int amount = Integer.parseInt(am);
            int pin1 = Integer.parseInt(p);
            int ag = Integer.parseInt(agentno);
            
           System.out.println(agentno);
            
            PreparedStatement ps2 =conn.prepareStatement("INSERT INTO `tbl_accounts`(`user_id`, `acc_no`, `type`, `balance`, `pin`, `status`, `agentaccountno`, `loan`, `opendate`, `expriydate`, `accountamount`, `nominal`,`loandate`) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            ps2.setInt(1,risultato);
            ps2.setInt(2, n);
            String ty="sa";
            ps2.setString(3,ty);
            ps2.setInt(4,amount);
            ps2.setInt(5,pin1);
            String st="FALSE";
            ps2.setString(6,st);
            ps2.setInt(7,ag);
            int lo=0;
            ps2.setInt(8,lo);
            ps2.setString(9,exp);
            ps2.setString(10, output);
            ps2.setInt(11, amount);
            ps2.setString(12,nominal);
            String ld="no";
            ps2.setString(13,ld);
            ps2.executeUpdate();
            
            
//generate uniqe transation number
String ni="TX";
Random ran1=new Random();
int n1=100000+ran1.nextInt(900000);
String tn=ni+n1;

String des="Credeted in your account"+amount+"by admiin";

//insert amount value into transation

PreparedStatement ps3 =conn.prepareStatement("INSERT INTO `tbl_transaction`(`tx_no`, `tx_type`, `amount`, `date`, `description`, `to_accno`, `status`, `agentaccountno`) VALUES(?,?,?,?,?,?,?,?)");
ps3.setString(1,tn);
ps3.setString(2,"credit");
ps3.setInt(3,amount);
ps3.setString(4,exp);
ps3.setString(5,des);
ps3.setInt(6,n);
ps3.setString(7,"SUCCESS");
ps3.setInt(8,ag);
ps3.executeUpdate();


//insert ad amount into agent table
PreparedStatement ps4=conn.prepareStatement("SELECT `balance` FROM `tbl_agentaccount` WHERE `accountno`=?");
ps4.setString(1,agentno);
ResultSet result2=ps4.executeQuery();

if(result2.next())
{
    bal1=result2.getInt("balance");
}

//balance calculation

System.out.println("bal"+bal1);
System.out.println("amount"+amount);

int total=amount+bal1;
System.out.println("total"+total);

//Update  amount into agent table
Statement stmt = null;
stmt = conn.createStatement();
String query = "UPDATE `tbl_agentaccount` SET `balance`='"+total+"' WHERE `accountno` = "+agentno;
stmt.executeUpdate(query);



validation=2;

        }
        if(validation==2)
        {
            String pt1 = "<html><body width='";
            String pt2 =
                    "'><h1>Registration Sucessfull</h1>" +
                    "<p>Name:"+ fname+""+lname+
                    " <br>Your account no: " +n+
                    "<br>Your Password : " +pass+
                    "";
            int width = 175;
            String s = pt1 + width + pt2 + width ;
            
            JOptionPane.showMessageDialog(null, s);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Some erroe occure in validation");
        }
    }
    catch(Exception ex){
        ex.printStackTrace();
    }
    
}

      } catch (ParseException ex) {
            Logger.getLogger(oppenaccount.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        clear();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(oppenaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(oppenaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(oppenaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(oppenaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new oppenaccount().setVisible(true);
            }
        });
    }
    
    public void clear()
    {
     cfname.setText("");
      clname.setText("");
       cpass.setText("");
        ccpass.setText("");
         cemail.setText("");
         cphone.setText("");
        
          cgender.setSelectedIndex(0);
          cadd.setText("");
          ccity.setText("");
          ccountry.setText("");
          cstate.setText("");
          czip.setText("");
          
         camount.setText("");
          pin.setText("");
          cnominal.setText("");
          
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea cadd;
    private javax.swing.JTextField camount;
    private datechooser.beans.DateChooserCombo caopendate;
    private javax.swing.JTextField ccity;
    private javax.swing.JTextField ccountry;
    private javax.swing.JTextField ccpass;
    private datechooser.beans.DateChooserCombo cdob;
    private javax.swing.JTextField cemail;
    private javax.swing.JTextField cfname;
    private javax.swing.JComboBox<String> cgender;
    private javax.swing.JTextField clname;
    private javax.swing.JTextField cnominal;
    private javax.swing.JTextField cpass;
    private javax.swing.JTextField cphone;
    private javax.swing.JLabel cphoto;
    private javax.swing.JTextField cstate;
    private javax.swing.JTextField czip;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private datechooser.beans.DateChooserDialog dateChooserDialog3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel nominal;
    private javax.swing.JTextField pin;
    public static javax.swing.JLabel uid1;
    // End of variables declaration//GEN-END:variables
}
